### ISSUE TITLE
Polyline2D calculate distance doesn't work properly

### ISSUE THREAD

**Issue by vocedar** [dlegland/javaGeom#13]
When I calculating the distance using Polyline2D.distance().

```

ArrayList<Point2D> listPoint= new ArrayList<>();
listPoint.add(new Point2D(201093.16610711772, 1777477.3696508463)); // UTM Easting and Northing converted from lat,lng
listPoint.add(new Point2D(202667.84818503872, 1777673.8963489647));

Polyline2D polyline = Polyline2D.create(listPoint);
Point2D currentPoint = new Point2D(201926.0433899812, 1777926.9596233366);

double distance = polyline.distance(currentPoint);
```
Result is not correct. 
But when I divided each coordinate by 1000, the result seem correct.
Is there any issue or I just missing somethings?

**Comment by dlegland** [comment]
Hi,

I think this is an issue...
Comparison of points with close but large coordinates may lead to propagation of uncertainties in computations. I will try to have a look.

**Comment by dlegland** [comment]
Hi,
I could not reproduce....

I have tried the following code, based on the one you have provided:

        ArrayList<Point2D> listPoint= new ArrayList<>();
        listPoint.add(new Point2D(201093.16610711772, 1777477.3696508463)); 
        listPoint.add(new Point2D(202667.84818503872, 1777673.8963489647));
        Polyline2D polyline = Polyline2D.create(listPoint);
        Point2D currentPoint = new Point2D(201926.0433899812, 1777926.9596233366);
        double dist1 = polyline.distance(currentPoint);
        System.out.println("distance1: " + dist1);
        
        ArrayList<Point2D> listPoint2= new ArrayList<>();
        listPoint2.add(new Point2D(201.09316610711772, 1777.4773696508463));
        listPoint2.add(new Point2D(202.66784818503872, 1777.6738963489647));

        Polyline2D polyline2 = Polyline2D.create(listPoint2);
        Point2D currentPoint2 = new Point2D(201.9260433899812, 1777.9269596233366);
        double dist2 = polyline2.distance(currentPoint2);
        System.out.println("distance2: " + dist2*1000);

I got the following output;

     distance1: 342.98267937936123 
     distance2: 342.9826793794603

Do you have the same?

**Comment by vocedar** [comment]
Run your code above but I got different results (tried both version 0.11.1 and 0.11.2):
```
distance1: 783.782734439939
distance2: 342.9826793794603
```

**Comment by dlegland** [comment]
Hi,
I have made a new release (0.11.3), to make sure an up-to-date jarfile is provided.

Can you check with this release if you still get the bug?

**Comment by vocedar** [comment]
I've tested the 0.11.3 version  and it work.
Thank you so much.

**Comment by dlegland** [comment]
Great! I'm glad it finally worked.
