### ISSUE TITLE
Performance: Add sqDistance function

### ISSUE THREAD

**Issue by ChristianLutz** [dlegland/javaGeom#14]
Hello,

assume you have million of points and you would like to find the point closest to line, polygon ...
It would be a lot faster if you could just calculate the square distance. And find smallest square distance value. With this it is possible to save for each distance calculation at least one `Math.hypot()`.

kind regards
Christian

**Comment by dlegland** [comment]
Hello,

yes, I agree. It should not be too complicated to add, I try to have a look soon!

Best regards,
David

**Comment by dlegland** [comment]
Hi,
implemented in commit 7f49cbc6930a2e315e73593336121cdaa6b399bd .

I am not sure however that the gain will always be large. For some shapes, the number of operations involved may be large, and the hypot came only at the end. But for points or lines, this should be better.

**Comment by ChristianLutz** [comment]
Thank you very much. This was fast.
