### ISSUE TITLE
math package problems in Scala

### ISSUE THREAD

**Issue by patrykcelinski** [dlegland/javaGeom#16]
It's very common for scala developers to use the scala.math package without the scala prefix as it's imported by default. Naming your package math conflicts with this such that simply JavaGeom as a dependency will break the build - it can't find math.max, math.round etc. Maybe you should have prefixed it with your own package to avoid these conflicts? Could the library use some package e.g. dlegland.javageom.math or just javageom.math so it can be also used in Scala?

**Comment by dlegland** [comment]
Hi patryk, 

well, this will beak compatibility with previous releases, but I agree this is a good idea to have a better prefix. I will update this.

**Comment by dlegland** [comment]
Hi,
I finally fixed it in commit https://github.com/dlegland/javaGeom/commit/0a0648575baf06c97986cdfd532ba545252f96fe

Will plan a new release in some time.

Best,
David
