### ISSUE TITLE
StraightLine intersection doesn't work properly.

### ISSUE THREAD

**Issue by ChristianLutz** [dlegland/javaGeom#4]
Hello,

I found some cases where the StraightLine2D intersection doesn't work. I added a test case to reproduce this. I would expect that for all lines (1-4) an intersection occurs.

```
@Test
public void javaGeomIntersection() {

    StraightLine2D line2d = new StraightLine2D(110337.28297120638, 48934.88776858141, 1650.316028793619, 1052.3122314185894);

    StraightLine2D line1 = new StraightLine2D(110083.599, 47397.2, 3808.0, 0.0);
    StraightLine2D line2 = new StraightLine2D(113891.599, 47397.2, 0.0, 5180.0);
    StraightLine2D line3 = new StraightLine2D(113891.599, 52577.2, -3808.0, 0.0);
    StraightLine2D line4 = new StraightLine2D(110083.599, 52577.2, 0.0, -5180.0);

    assertNotNull(line2d.intersection(line1));
    assertNotNull(line2d.intersection(line2));
    assertNotNull(line2d.intersection(line3));
    assertNotNull(line2d.intersection(line4));
}
```

If you need any further information just let me know.

**Comment by dlegland** [comment]
Hi Christian,
Thanks for reporting the problem. I agree, an intersection should occur... 
I think there is a problem at the end of the function computing the intersection point. There is a test to check whether the intersection point belongs to the line (useful for computing intersection of line segments), but it seems to be problematic with large numbers... I'll investigate this.

**Comment by dlegland** [comment]
Hi,
I have commited a fix, that makes the sample test code to pass. Let me know if you encounter other similar problems.

**Comment by ChristianLutz** [comment]
Thank you for the fast fix.
