### ISSUE TITLE
LineSegment distance doesn't work if LineSegment2D is based on identical points 

### ISSUE THREAD

**Issue by ChristianLutz** [dlegland/javaGeom#7]
Hello,

the following test fails, because the LineSegment2D has been created with two identical points. 
In my opionen it is fine to create a line segment with two identical points in contrast to a straight line. If so the distance should still be possible. 

```
@Test
public void javaGeomLineSegment2DDistanceTest() {
    final LineSegment2D lineA = new LineSegment2D(244059.964, 151370.04000000003, 244059.964, 151370.04000000003);
    lineA.distance(new Point2D(246599.964, 151370.03000000003));
}
```

sincerely
christian

**Comment by dlegland** [comment]
I agree, a LineSegment2D should exist even if both extremities are the same. Well, this makes things more complex for fixing, but I will check this.

**Comment by dlegland** [comment]
Hi,
I have commited some changes that should fix it. Tell me if you still have some pbms!
